name: thesillyhome addon dev
version: "0.0.1-alpha"
slug: thesillyhome_dev
description: "thesillyhome add-on cloud"
url: "https://github.com/lcmchris/thesillyhome-addon-repo"
homeassistant_api: true
init: false
environment:
  HA_ADDON: "true"
map:
  - config:ro
arch:
  - amd64
  - armv7
  - aarch64
options:
  api_key:
    - ey.xxxx.xxxx
  actuactors_id:
    - light.bathroom_lights
    - light.corridor_lights
    - switch.livingroom_entrance_switch_right
    - switch.livingroom_entrance_switch_center
    - switch.livingroom_entrance_switch_left
    - light.bedroom_sidetable_lamp
    - light.bedroom_ceiling_light
  db_options:
    - db_password: XXXXXXX
      db_username: homeassistant
      db_host: 192.168.1.100
      db_port: "3306"
      db_database: homeassistant
      db_type: mariadb
  autotrain: true
  autotrain_cadence: "0 0 * * 0"
schema:
  api_key:
    - str
  actuactors_id:
    - str
  db_options:
    - db_password: str?
      db_username: str?
      db_host: str?
      db_port: str?
      db_database: str
      db_type: str
  autotrain: bool
  autotrain_cadence: str
# image: "lcmchris1/{arch}-thesillyhome-addon-cloud"
