name: smartvent addon dev lightningpicture
version: "init2"
slug: smartvent_dev
description: "AI-powered ventilation control based on humidity, temperature, and weather."
url: "https://github.com/lightningpicture/smartvent-addon-repo"
homeassistant_api: true
ingress: true
ingress_port: 8088
ingress_entry: Controls
panel_icon: "mdi:home-thermometer"
panel_title: "SmartVent Addon"
init: false
ports:
  8088/tcp: 8088
ports_description:
  8088/tcp: "Web interface (not required for Home Assistant ingress)"
environment:
  HA_ADDON: "true"
map:
  - config:ro
arch:
  - amd64
  - armv7
  - aarch64
options:
  humidity_sensor_id:
    - sensor.humidity_livingroom
    - sensor.humidity_bathroom
  temperature_sensor_id:
    - sensor.temp_livingroom
    - sensor.temp_bathroom
  brightness_sensor_id:
    - sensor.light_livingroom
  heating_sensor_id:
    - sensor.heating
  weather_station_id:
    - sensor.weather_station
  person_sensor_id:
    - binary_sensor.person_livingroom
  ventilation_id:
    - switch.lueftung_badezimmer  # Entity ID der L端ftungseinheit im Badezimmer
    - switch.lueftung_kuche       # Entity ID der L端ftungseinheit in der K端che
  min_humidity: 60
  max_humidity: 70
  min_temperature: 18
  max_temperature: 22
  learn_rate: 0.01
  port: 8088
  timeout: 10  # Timeout f端r API-Anfragen
  autotrain: true
  autotrain_cadence: "35 * * * *"
  startup_disable_all: false
schema:
  humidity_sensor_id:
    - str
  temperature_sensor_id:
    - str
  brightness_sensor_id:
    - str
  heating_sensor_id:
    - str
  weather_station_id:
    - str
  person_sensor_id:
    - str
  ventilation_id:
    - str
  min_humidity: int
  max_humidity: int
  min_temperature: int
  max_temperature: int
  learn_rate: float
  port: int
  timeout: int
  autotrain: bool
  autotrain_cadence: str
  startup_disable_all: bool
image: "lightningpicture/smartvent"
